### ISSUE TITLE
fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by kucharskim** [microtick/mtzone#6]
```
microtick_1  | 11:11PM INF committed state app_hash=66C07BA28F33D80E5E7DE90C26E0C02DEC0D695CFA26C2FAA0015B239957C2BA height=2432628 module=state num_txs=18
microtick_1  | 11:11PM INF indexed block height=2432628 module=txindex
microtick_1  | fatal error: concurrent map read and map write
microtick_1  | 
microtick_1  | goroutine 1734569688 [running]:
microtick_1  | runtime.throw({0x198c0f4, 0xc00014fc10})
microtick_1  |  /usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc002280c10 sp=0xc002280be0 pc=0x43af51
microtick_1  | runtime.mapaccess1_fast64(0xe1f12e, 0x1750040, 0x251e74)
microtick_1  |  /usr/local/go/src/runtime/map_fast64.go:21 +0x172 fp=0xc002280c30 sp=0xc002280c10 pc=0x416bf2
microtick_1  | github.com/cosmos/iavl.(*MutableTree).VersionExists(0xc000f4a250, 0x1da9380)
microtick_1  |  /go/pkg/mod/github.com/cosmos/iavl@v0.16.0/mutable_tree.go:63 +0xae fp=0xc002280c68 sp=0xc002280c30 pc=0xd6134e
microtick_1  | github.com/cosmos/cosmos-sdk/store/iavl.(*Store).VersionExists(...)
microtick_1  |  /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/store/iavl/store.go:144
microtick_1  | github.com/cosmos/cosmos-sdk/store/iavl.(*Store).GetImmutable(0xc0010cf340, 0x1da9380)
microtick_1  |  /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/store/iavl/store.go:92 +0x35 fp=0xc002280ca0 sp=0xc002280c68 pc=0xd802d5
microtick_1  | github.com/cosmos/cosmos-sdk/store/rootmulti.(*Store).CacheMultiStoreWithVersion(0xc000c90320, 0x0)
microtick_1  |  /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/store/rootmulti/store.go:433 +0x216 fp=0xc002280fb0 sp=0xc002280ca0 pc=0xd89a16
microtick_1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).createQueryContext(_, _, _)
microtick_1  |  /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/baseapp/abci.go:635 +0x17c fp=0xc002281968 sp=0xc002280fb0 pc=0xfb763c
microtick_1  | github.com/cosmos/cosmos-sdk/baseapp.handleQueryCustom(0xc00001c9c0, {0xc00f543f50, 0x3, 0x0}, {{0xc01c3c6f00, 0x40, 0x40}, {0xc0016f6c30, 0x2c}, 0x251e74, ...})
microtick_1  |  /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/baseapp/abci.go:851 +0x1b0 fp=0xc0022822e0 sp=0xc002281968 pc=0xfb8b50
microtick_1  | github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Query(0xc00001c9c0, {{0xc01c3c6f00, 0x40, 0x40}, {0xc0016f6c30, 0x2c}, 0x251e74, 0x0})
microtick_1  |  /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/baseapp/abci.go:438 +0x56f fp=0xc002282548 sp=0xc0022822e0 pc=0xfb55cf
microtick_1  | github.com/microtick/mtzone/app.(*MicrotickApp).Query(0xc000eac800, {{0xc01c3c6f00, 0x40, 0x40}, {0xc0016f6c30, 0x2c}, 0x0, 0x0})
microtick_1  |  <autogenerated>:1 +0xdc fp=0xc002282698 sp=0xc002282548 pc=0x15db55c
microtick_1  | github.com/tendermint/tendermint/abci/client.(*localClient).QuerySync(0xc000123440, {{0xc01c3c6f00, 0x40, 0x40}, {0xc0016f6c30, 0x2c}, 0x0, 0x0})
microtick_1  |  /go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/abci/client/local_client.go:258 +0x171 fp=0xc002282828 sp=0xc002282698 pc=0xcde451
microtick_1  | github.com/tendermint/tendermint/proxy.(*appConnQuery).QuerySync(0x2c, {{0xc01c3c6f00, 0x40, 0x40}, {0xc0016f6c30, 0x2c}, 0x0, 0x0})
microtick_1  |  /go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/proxy/app_conn.go:159 +0x6e fp=0xc002282878 sp=0xc002282828 pc=0xce24ee
microtick_1  | github.com/tendermint/tendermint/rpc/core.ABCIQuery(0x16deec0, {0xc0016f6c30, 0x5b5d2f}, {0xc01c3c6f00, 0x16deec0, 0x4127d4}, 0xc0021b09a0, 0x98)
microtick_1  |  /go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/rpc/core/abci.go:20 +0xb2 fp=0xc002282910 sp=0xc002282878 pc=0xf46692
microtick_1  | github.com/tendermint/tendermint/rpc/client/local.(*Local).ABCIQueryWithOptions(0x0, {0x30, 0x7ffff7da75b8}, {0xc0016f6c30, 0xc000072c00}, {0xc01c3c6f00, 0x0, 0x5b58d0}, {0x0, 0x0})
microtick_1  |  /go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/rpc/client/local/local.go:87 +0x45 fp=0xc002282960 sp=0xc002282910 pc=0xf99f05
microtick_1  | github.com/cosmos/cosmos-sdk/client.Context.queryABCI({{0x0, 0x0, 0x0}, {0x1e0e770, 0xc001b44140}, {0xc001b00cd0, 0xb}, {0x1ddead0, 0xc00100c940}, {0x1de9600, ...}, ...}, ...)
microtick_1  |  /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/client/query.go:79 +0x19e fp=0xc002282c50 sp=0xc002282960 pc=0xdd26be
microtick_1  | github.com/cosmos/cosmos-sdk/client.Context.query({{0x0, 0x0, 0x0}, {0x1e0e770, 0xc001b44140}, {0xc001b00cd0, 0xb}, {0x1ddead0, 0xc00100c940}, {0x1de9600, ...}, ...}, ...)
microtick_1  |  /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/client/query.go:113 +0x119 fp=0xc002282f98 sp=0xc002282c50 pc=0xdd2d59
microtick_1  | github.com/cosmos/cosmos-sdk/client.Context.QueryWithData(...)
microtick_1  |  /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/client/query.go:42
microtick_1  | github.com/cosmos/cosmos-sdk/x/staking/client/rest.queryDelegator.func1({0x1db8c90, 0xc00f1fb428}, 0xc016dd4840)
microtick_1  |  /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/x/staking/client/rest/utils.go:99 +0x2c7 fp=0xc0022836b0 sp=0xc002282f98 pc=0x14f5da7
microtick_1  | net/http.HandlerFunc.ServeHTTP(0x1844c60, {0x1db8c90, 0xc00f1fb428}, 0x7)
microtick_1  |  /usr/local/go/src/net/http/server.go:2046 +0x2f fp=0xc0022836d8 sp=0xc0022836b0 pc=0x90550f
microtick_1  | github.com/cosmos/cosmos-sdk/client/rest.addHTTPDeprecationHeaders.func1({0x1db8c90, 0xc00f1fb428}, 0xc00f543260)
microtick_1  |  /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.42.9/client/rest/rest.go:21 +0x24c fp=0xc002283760 sp=0xc0022836d8 pc=0x101da2c
microtick_1  | net/http.HandlerFunc.ServeHTTP(0xc002182600, {0x1db8c90, 0xc00f1fb428}, 0xc002b05828)
microtick_1  |  /usr/local/go/src/net/http/server.go:2046 +0x2f fp=0xc002283788 sp=0xc002283760 pc=0x90550f
microtick_1  | github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001fd980, {0x1db8c90, 0xc00f1fb428}, 0xc002182500)
microtick_1  |  /go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf fp=0xc0022838b0 sp=0xc002283788 pc=0xddb1ef
microtick_1  | github.com/tendermint/tendermint/rpc/jsonrpc/server.maxBytesHandler.ServeHTTP({{0x1d9af20, 0xc0001fd980}, 0x412b27}, {0x1db8c90, 0xc00f1fb428}, 0xc002182500)
microtick_1  |  /go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/rpc/jsonrpc/server/http_server.go:236 +0x122 fp=0xc002283910 sp=0xc0022838b0 pc=0xde7ca2
microtick_1  | github.com/tendermint/tendermint/rpc/jsonrpc/server.(*maxBytesHandler).ServeHTTP(0xc0016dc4f8, {0x1db8c90, 0xc00f1fb428}, 0xd)
microtick_1  |  <autogenerated>:1 +0x53 fp=0xc002283950 sp=0xc002283910 pc=0xdeda33
microtick_1  | github.com/tendermint/tendermint/rpc/jsonrpc/server.RecoverAndLogHandler.func1({0x1db92f0, 0xc0122fc1c0}, 0xc002182500)
microtick_1  |  /go/pkg/mod/github.com/tendermint/tendermint@v0.34.13/rpc/jsonrpc/server/http_server.go:209 +0x38a fp=0xc002283a98 sp=0xc002283950 pc=0xde6d8a
microtick_1  | net/http.HandlerFunc.ServeHTTP(0x0, {0x1db92f0, 0xc0122fc1c0}, 0x46c1ee)
microtick_1  |  /usr/local/go/src/net/http/server.go:2046 +0x2f fp=0xc002283ac0 sp=0xc002283a98 pc=0x90550f
microtick_1  | net/http.serverHandler.ServeHTTP({0xc00f5430e0}, {0x1db92f0, 0xc0122fc1c0}, 0xc002182500)
microtick_1  |  /usr/local/go/src/net/http/server.go:2878 +0x43b fp=0xc002283b80 sp=0xc002283ac0 pc=0x908f3b
microtick_1  | net/http.(*conn).serve(0xc01257f5e0, {0x1dd6e58, 0xc002459140})
microtick_1  |  /usr/local/go/src/net/http/server.go:1929 +0xb08 fp=0xc002283fb8 sp=0xc002283b80 pc=0x9045e8
microtick_1  | net/http.(*Server).Serve·dwrap·82()
microtick_1  |  /usr/local/go/src/net/http/server.go:3033 +0x2e fp=0xc002283fe0 sp=0xc002283fb8 pc=0x90988e
microtick_1  | runtime.goexit()
microtick_1  |  /usr/local/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc002283fe8 sp=0xc002283fe0 pc=0x46e3c1
microtick_1  | created by net/http.(*Server).Serve
microtick_1  |  /usr/local/go/src/net/http/server.go:3033 +0x4e8
microtick_1  | 
```

**Comment by kucharskim** [comment]
More logs at https://generic.mp/r/drib-viqw-nlf5-yi2k-zheu-yr63-nb6a/

**Comment by kucharskim** [comment]
```
$ mtm version
mtm v2 (mtm-v2-rc4-31-g5748a8d)
```

**Comment by mark-microtick** [comment]
This is a very old version of mtm - recommend upgrading to 2.0.5 here https://microtick.com/releases/mainnet

The concurrent map read write error was fixed by upgrading to a newer SDK version.

**Comment by mark-microtick** [comment]
That commit appears to be on @joe-bowman 's branch - we probably need to rebase to master to grab the newer SDK version.

**Comment by kucharskim** [comment]
Source code here https://github.com/microtick/mtzone/releases/tag/mtm-v2.0.5 - right?

**Comment by mark-microtick** [comment]
That should be correct, yes

**Comment by kucharskim** [comment]
We are running on v2.0.5 now. Will re-open if we see this problem again. Thanks!
